###admin login
POST https://blogapplicationnn.onrender.com/auth/login
Content-Type: application/json

{
  "email":"admin@gmail.com",
  "password":"admin"
}
###read all user and authors (email)


###block or activate user or author 



###change password
PUT https://blogapplicationnn.onrender.com/auth/password
Content-Type: application/json

{
  "currentPassword":"admin",
  "newPassword":"admin1"
}
