### Register author
POST https://blogbackend-ujb1.onrender.com/auth/users
Content-Type: application/json

{
  "firstName": "author2",
  "lastName": "",
  "email": "author2@mail.com",
  "role":"AUTHOR",
  "password": "author2",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### Create new Article
POST https://blogbackend-ujb1.onrender.com/author-api/article
Content-Type: application/json

{
  "author":"69b44fcc14255c6f0d1f7b9b",
  "title":"Article-2 by Author 2",
  "category":"CSE",
  "content":"test article on CSE"
  
}

### Author Login
POST https://blogbackend-ujb1.onrender.com/auth/login
Content-Type: application/json

{
  "email":"author1@mail.com",
  "password":"author1"
}

### Author logout
GET https://blogbackend-ujb1.onrender.com/auth/logout

### Read own articles
GET https://blogbackend-ujb1.onrender.com/author-api/articles

### Update article by author
PUT https://blogbackend-ujb1.onrender.com/author-api/articles
Content-Type: application/json

{
  "articleId":"69b3c780ad975da58dbd3ba1",
  "title":"Article-2 by Author 1",
  "category":"AI",
  "content":"test article on AI and its updated"
  
}

### Delete / restore an article by Article ID (soft delete)
PATCH https://blogbackend-ujb1.onrender.com/author-api/articles
Content-Type: application/json

{
  "articleId":"69b3a8f881ab391ebe9a7435",
  "isArticleActive":true
}

###change password
PUT https://blogbackend-ujb1.onrender.com/auth/password
Content-Type: application/json

{
  "currentPassword":"author1",
  "newPassword":"author"
}
