### Register User
POST https://blogbackend-ujb1.onrender.com/auth/users
Content-Type: application/json

{
  "firstName": "user2",
  "lastName": "",
  "email": "user2@mail.com",
  "role":"USER",
  "password": "user2",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### User Login
POST https://blogbackend-ujb1.onrender.com/auth/login
Content-Type: application/json

{
  "email":"user1@mail.com",
  "password":"user1"
}

###read articles of all authors
GET https://blogbackend-ujb1.onrender.com/user-api/articles

###add comment by user to an article
PUT https://blogbackend-ujb1.onrender.com/user-api/articles
Content-Type: application/json

{
  "articleId":"69b44fd614255c6f0d1f7b9f",
  "comment":"excellent article by author 1"
}

### User logout
GET http://localhost:4000/auth/logout

###change password
PUT https://blogbackend-ujb1.onrender.com/auth/password
Content-Type: application/json

{
  "currentPassword":"user1",
  "newPassword":"user"
}
